pyensembl/gene.py, pyensembl/locus.py, pyensembl/reference_transcripts.py, pyensembl/transcript.py, setup.py
Fixes https://github.com/hammerlab/pyensembl/issues/23
Also:
* check validity of gene_biotype on Gene object
* sped up `__contains__` and sequence access on `ReferenceTranscripts` by by-passing `pyfaidx.Fasta.__contains__` (which copies a list of keys every time) 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/26)
=> changed @property (with ad-hoc hasattr caching) to instead use memoized-property library

README.md, pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/gtf.py, pyensembl/reference_transcripts.py, pyensembl/shell.py, pyensembl/transcript.py, requirements.txt, setup.py, test/test_common.py, test/test_compute_cache.py, test/test_dataframe_release75.py, test/test_download.py, test/test_exon_id.py, test/test_exon_object.py, test/test_gene_id.py, test/test_gene_ids.py, test/test_gene_names.py, test/test_reference_transcripts.py, test/test_release_versions.py, test/test_transcript_ids.py, test/test_transcript_ids_at_locus.py
Make downloads explicit (unless `auto_download` is `True`). An Exception is raised if the necessary data isn't present, and users can either use the shell or python to run the downloads. Fixes #31 
Relies on https://github.com/hammerlab/datacache/pull/7
A few questions that come to mind:
- Did I hook into the right places?
- Do you think the `varcode` should also have an `auto_download` flag to send along to `pyensembl`?
TODO:
- Tests
- README update
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/34)
=> Make downloads explicit

test/test_timings.py, test/timer.py
Currently only testing performance of  `genes_at_locus`, `transcripts_at_locus`, `exons_at_locus` but should be easy to add more later. Also, there's a hackish search through the globals dict to find all benchmarks when they're being run outside of nose. If we need to reuse that trick elsewhere, I'll factor it out into its own module. 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/48)
=> added Timer class and benchmark unit tests

pyensembl/database.py, pyensembl/gtf.py, pyensembl/shell.py
* `pyensembl` commandline utility now works in Python 3.
* more intuitive syntax, better help.
* fix error messages elsewhere to give correct pyensembl command to run to install ensembl release data.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/61)
=> Cleanup pyensembl commandline utility

pyensembl/biotypes.py, pyensembl/gtf.py, pyensembl/gtf_parsing.py, pyensembl/transcript.py, pyensembl/url_templates.py, setup.py
* Ensembl 79's GTF added another surprise: entries in the last column with multiple spaces. This isn't really their fault, since the spaces were within quotes. Added a bandaid fix, but need to implement a real parser before Ensembl 80 comes out. 
* Added some missing biotypes. 
* PEP8 fixes in `gtf_parsing`
* Fixed FASTA path for protein sequences for Ensembl releases <= 75
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/81)
=> Fix release 79

pyensembl/common.py, pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/exon.py, pyensembl/gene.py, pyensembl/locus.py, pyensembl/transcript.py, setup.py, test/test_exon_object.py, test/test_gene_objects.py, test/test_locus.py, test/test_transcript_objects.py
Make sure we never construct the same `Transcript` or `Exon` object twice by routing through `EnsemblRelease.exon_by_id` and `EnsemblRelease.transcript_by_id`. This not only cuts down on the cost of initialization but makes sure we don't recompute cached properties.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/84)
=>  Routing Exon and Transcript construction through memoized methods

pyensembl/common.py, pyensembl/sequence_data.py, setup.py, test/test_sequence_data.py, test/test_transcript_sequences.py
* `skbio.parse_fasta` is deprecated (and seems to be missing entirely from the latest pip version), using `skbio.read`
* Similarly, using `skbio.DNA` instead of `skbio.DNASequence`
* Got rid of expectation that sequences returned by `SequenceData` should have `complement()` method (still undecided whether these should be `str` or `skbio.Sequence` objects, Varcode wants to concatenate sequences which skbio doesn't support)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/117)
=> Update deprecated skbio functionality to newer equivalnets

.travis.yml
The last deploy failed because it wasn't tagged
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/122)
=> Deploy to PyPi on every master commit

.travis.yml, requirements.txt, setup.py
Added pandoc to installed packages on Travis and remove requirement for `mock`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/129)
=> +pandoc, -mock

pyensembl/biotypes.py, pyensembl/sequence_data.py, pyensembl/transcript.py, setup.py, test/test_transcript_sequences.py
* Transcript.coding_sequence should return None rather than trying to slice into an empty `Transcript.sequence`
* It was impossible to look up sequences in Ensembl 83 since they added a version number to every FASTA key (added a test for this)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/136)
=> Transcript.coding_sequence didn't work for non-coding transcripts

pyensembl/ensembl_release.py, pyensembl/gene.py, pyensembl/genome.py, pyensembl/species.py, pyensembl/transcript.py, setup.py, test/test_pickle.py
This will allow `varcode.EffectCollection` to get pickled.
Threw in equals and hashing for species because that was needed for the pickling tests to run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/137)
=> Add pickling for several classes

pyensembl/__init__.py, pyensembl/genome.py, pyensembl/locus.py, setup.py, test/common.py, test/test_contigs.py, test/test_locus.py, test/test_transcript_objects.py
Fixed bug in `normalize_chromosome` where lowercase mitochondrial names were sneaking through. 
Also fixed https://github.com/hammerlab/pyensembl/issues/139 by making `Genome.all_feature_values` private. 
Added unit test for newly added `Genome.contigs()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/144)
=> fixed normalize_chromosome, made all_feature_values private

README.md, pyensembl/download_cache.py, test/test_download_cache.py
so that we can write the cache to a shared directory when running analyses on multi-node clusters.
Context: https://github.com/hammerlab/biokepi/pull/268
cc: @arahuja and @seb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/156)
=> Override cache dir if PYENSEMBL_CACHE_DIR is set

pyensembl/__init__.py, pyensembl/ensembl_release.py, test/test_serialization.py
* Moved contents of `cached_release` onto the EnsemblRelease object (`EnsemblRelease.cached`)
* Using `WeakValueDictionary` instead of ordinary dict to avoid memory leak
* Added `from_dict` class method to use `cached` for deserialization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/163)
=> Deserialization should construct cached EnsemblRelease objects

pyensembl/__init__.py, test/test_gene_objects.py, test/test_transcript_objects.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/166)
=> Added protein coding biotype tests

RELEASING.md, pyensembl/__init__.py, pyensembl/database.py, pyensembl/download_cache.py, pyensembl/fasta.py, pyensembl/genome.py, pyensembl/gtf.py, pyensembl/logging.conf, pyensembl/memory_cache.py, pyensembl/sequence_data.py, pyensembl/shell.py, requirements.txt, setup.py
fixes #170, #172 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/171)
=> one logger per module

.travis.yml, pyensembl/__init__.py, pyensembl/common.py, pyensembl/download_cache.py, pyensembl/ensembl_release.py, pyensembl/ensembl_release_versions.py, pyensembl/ensembl_url_templates.py, pyensembl/fasta.py, pyensembl/genome.py, pyensembl/locus_with_genome.py, pyensembl/normalization.py, pyensembl/reference_name.py, pyensembl/search.py, pyensembl/sequence_data.py, pyensembl/shell.py, pyensembl/species.py, pyensembl/transcript.py, requirements.txt, setup.py, test/test_missing_genome_sources.py
The main change here is that it's now possible to check whether a `Genome` has all of its required resources locally installed and this feature is used to iterate through every possible Ensembl release associated with a reference genome and use the most recent locally installed. This fixes the annoying scenario where we update the MAX_ENSEMBL_RELEASE and then break every downstream package which installs the wrong Ensembl release for its tests.  
Also fixes: https://github.com/openvax/pyensembl/issues/188
=> Don't require users to download latest Ensembl every time we bump the MAX_ENSEMBL_RELEASE

.travis.yml, pyensembl/__init__.py
External contributors can't currently submit PRs from forks and have their unit tests run since Travis doesn't expose encrypted values outside of the `openvax` organization. There were some attempts to negotiate a solution in 2014 which seem to have fizzled: https://github.com/travis-ci/travis-ci/issues/1946
So, to re-enable external PRs, I'm dropping our private MHC binding predictors and relying exclusively on MHCflurry, "random" and "iedb-*" predictors.
=> removing encrypted values from Travis

pyensembl/__init__.py, pyensembl/genome.py, pyensembl/transcript.py, test/test_transcript_support_level.py
GRCh38 database provides a field called `transcript_support_level` (TSL) for transcript features. This PR adds reading of it as an optional field, and adds a new `support_level` field for `Transcript` object.
=> Add transcript_support_level (TSL) field

.travis.yml, pyensembl/__init__.py, pyensembl/exon.py, pyensembl/gene.py, pyensembl/locus.py, pyensembl/locus_with_genome.py, pyensembl/normalization.py, pyensembl/transcript.py, setup.py, test/data.py, test/test_serialization.py, test/test_string_representation.py, test/test_transcript_objects.py
'gene.exons` does not work on Py3 (https://github.com/openvax/pyensembl/issues/215) due to lack of comparison for `sorted`, fixing this by implementing basic comparison methods on Locus (base class for Exon).
=> Implemented comparison on Locus objects

pyensembl/__init__.py, pyensembl/normalization.py, pyensembl/reference_name.py, test/test_locus.py, test/test_ucsc_gtf.py
In the dark ages of PyEnsembl we needed a quick way to annotate variants from hg19 and GRCh37 using Ensembl reference data. This lead to a dirty chromosome normalization hack where we turn e.g. "chr1" -> "1" and "chrM" -> "MT". 
This was always a little questionable (since the mitochondrial sequences aren't actually the same) but even worse is incorrect for references like GRCh38. 
So, this PR gets rid of two aspects of contig normaliztion: "chr" prefix is now preserved and we don't convert "M" -> "MT" for the mitochondrial genome. 
Fixes: https://github.com/openvax/pyensembl/issues/225
To restore use of Ensembl data for hg19 variants we'll have to make a more local contig conversion option in Varcode.
=> Fix chrM / MT normalization

pyensembl/ensembl_url_templates.py
- Remove dependencies for urllib_parse and os.path.join. 
- Remove unused function make_fasta_dna_url. 
- Refactor path generation for remote files to better reflect the folder structure on the Ensembl FTP server.
Fixes #217.
=> Fix URL path generation issues for Windows 10 users.

pyensembl/transcript.py
Using release 69 of Ensembl, I ran into an issue where some transcripts existed which had an annotated start_codon that only spanned two positions (example ENST00000543092).
Because of this, when .complete() was run, self.coding_sequence would hit an error when it tried to determine the _codon_positions:
ValueError: Expected 3 positions for start_codon of ENST00000543092 but got 2
It seems that more recent releases of Ensembl do not have this issue (they no longer list a start_codon for these cases).
To continue using Ensembl 69, I added the additional property .start_codon_complete which catches a _codon_position ValueError and returns False, and added self.start_codon_complete as an additional check in .complete().
Fixes #231
=> Add check .start_codon_complete

pyensembl/ensembl_release_versions.py
105 is the latest release, while 104 is the currently enforced upper bound in the library.
=> bump ensembl release version

pyensembl/ensembl_url_templates.py
Error downloading ensembl files, used to work with ftp, now with https. Change in ensembl_url_templates.py
=> Update ensembl link to download file

requirements.txt
Pandas needed when running pyensembl install and will break if lower than this version.
=> Add pandas>=1.3.5 as requirement

README.md, pyensembl/download_cache.py, pyensembl/genome.py, pyensembl/species.py
1. Added usage tips in the README.md
2. Changed default parameter value for `download_if_missing` in [`_set_local_paths`](https://github.com/openvax/pyensembl/compare/master...rraadd88:pyensembl:dev?expand=1#diff-648b81ac48c81678e080c9d569cd0c78f243ed65f43a85ad772ebcac031c59c0R219) which now allows downloading files in interactive python.
3. Registered `saccharomyces_cerevisiae` as `yeast` in [`species.py`](https://github.com/openvax/pyensembl/compare/master...rraadd88:pyensembl:dev?expand=1#diff-fb115395175caaa3bb84deab38ce96cf45e60a4882a2cb34b9d7eaf117819d0dR319)
=> A few updates
