pyensembl/biotypes.py, pyensembl/gene.py, pyensembl/transcript.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/27)
=> reorganized biotype groupings, added lots of comments to biotypes file

pyensembl/database.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/29)
=> Importing a missing variable

pyensembl/locus.py, pyensembl/transcript.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/36)
=> don't use sequence to determine length, may not always be available

pyensembl/__init__.py, pyensembl/database.py, pyensembl/gene.py, pyensembl/locus.py, pyensembl/reference_transcripts.py, pyensembl/transcript.py, test/test_gene_objects.py, test/test_transcript_objects.py
.... Also added some comments to unit tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/37)
=> added __eq__ and __hash__ methods to Transcript, Gene, and other objects

pyensembl/type_checks.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/45)
=> Remove parens around assert

pyensembl/database.py, pyensembl/gtf.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/46)
=> fixed mixing up the local and remote filenames of GTF files

pyensembl/compute_cache.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/47)
=> fixed key vs. path typo in compute_cache

pyensembl/gtf.py
Fixes #49 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/50)
=> local_filename was missing the .gtf extension

.travis.yml, README.md, lint.sh, pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/gtf.py, pyensembl/locus.py, pyensembl/reference_transcripts.py, pyensembl/transcript.py, pyensembl/url_templates.py, pylintrc, requirements.txt, setup.py, test/test_compute_cache.py, test/test_dataframe_release75.py, test/test_download.py, test/test_exon_object.py, test/test_gene_id.py, test/test_gene_objects.py, test/test_gtf.py, test/test_locus.py, test/test_search.py, test/test_transcript_id.py, test/test_transcript_objects.py, test/timer.py
I figure we can work out how to make this faster later?
(Also, `pylint` fails on a whole bunch of stuff, but I'm thinking I can address that in a follow-up PR.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/44)
=> Adding Travis with pylint

pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/exon.py, pyensembl/gene.py, pyensembl/gtf.py, pyensembl/transcript.py, pyensembl/url_templates.py, setup.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/53)
=> Fix missing type checks module

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/54)
=> Travis isn't currently working

pyensembl/database.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/60)
=> don't use protein_id as primary key of CDS table

requirements.txt, setup.py, test/test_common.py, test/test_compute_cache.py, test/test_dataframe_release75.py, test/test_download.py, test/test_exon_id.py, test/test_exon_object.py, test/test_gene_id.py, test/test_gene_ids.py, test/test_gene_names.py, test/test_gene_objects.py, test/test_gtf.py, test/test_gtf_path.py, test/test_id_length.py, test/test_locus.py, test/test_reference_transcripts.py, test/test_release_versions.py, test/test_search.py, test/test_timings.py, test/test_transcript_id.py, test/test_transcript_ids.py, test/test_transcript_ids_at_locus.py, test/test_transcript_objects.py
* fix module imports in tests
* add mock package to requirements
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/63)
=> Make tests run in Python3

pyensembl/ensembl_release.py, pyensembl/release_info.py, setup.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/77)
=> fixed typo in protein_sequence, increased version, increased max Ensembl version to 79

pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/gtf.py, setup.py
Implementation of __hash__ needed for memoization (maybe only in Python 3?)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/83)
=> Make all PyEnsembl objects hashable

pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/exon.py, pyensembl/transcript.py, setup.py, test/test_transcript_objects.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/87)
=> Added "gene" property to Transcript objects which gives access to the parent Gene

pyensembl/__init__.py, pyensembl/common.py, pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/exon.py, pyensembl/gene.py, pyensembl/transcript.py, setup.py, test/test_common.py, test/test_gene_id.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/88)
=> print biotype as part of Transcript and Gene

pyensembl/ensembl_release.py, setup.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/89)
=> Better error on missing transcript

setup.py
Fixes https://github.com/hammerlab/pyensembl/issues/93
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/94)
=> Bump datacache version

pyensembl/common.py, pyensembl/locus.py
Cache locus.normalize_chromosome, small speedup to common.memoize
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/95)
=> Two small performance tweaks

README.md, pyensembl/compute_cache.py, pyensembl/database.py, pyensembl/ensembl_release.py, pyensembl/ensembl_release_source.py, pyensembl/gene.py, pyensembl/genome.py, pyensembl/genome_source.py, pyensembl/sequence_data.py, pyensembl/shell.py, pyensembl/transcript.py, setup.py, test/test_missing_genome_sources.py, test/test_transcript_objects.py
Addresses:
* https://github.com/hammerlab/pyensembl/issues/107
* https://github.com/hammerlab/pyensembl/issues/106 (with a bunch of related tests)
* https://github.com/hammerlab/pyensembl/issues/105
* https://github.com/hammerlab/pyensembl/issues/104
* https://github.com/hammerlab/pyensembl/issues/103
@iskandr: as for the `varcode.test.test_variants.test_serialization` issue that I mentioned, that appears to just be a manifestation of not downloading Ensembl 77 before running that test. I have a new varcode `mouse` branch commit that makes sure a few more things are auto-downloaded/installed: https://github.com/hammerlab/varcode/commit/68f98b3c6d0fd905ee4e6406f48cecfb0dbe85f4
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Fixes for various issues after the arbitrary GTF PR

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/121)
=> Add pyensembl build status to README

.travis.yml, README.md
(Self-explanatory)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/124)
=> Add coveralls to PyEnsembl

.travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/130)
=> Added installation of pypandoc to Travis config

.travis.yml, lint.sh, pyensembl/ensembl_url_templates.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/132)
=> Copied new travis config from Varcode

pyensembl/ensembl_release_versions.py, setup.py
...now we wait for tests to fail.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/134)
=> Increase the max Ensembl version to 83

.travis.yml, pyensembl/__init__.py, pyensembl/database.py, pyensembl/fasta.py, pyensembl/gtf.py, pyensembl/sequence_data.py, pyensembl/species.py, requirements.txt, setup.py, test/data.py, test/test_sequence_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/146)
=> Added NCBIM37 to list of references for mouse

pyensembl/__init__.py, pyensembl/biotypes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/149)
=> moved polymorphic_pseudogene to noncoding biotype group

pyensembl/__init__.py, pyensembl/ensembl_release_versions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/153)
=> Added support for Ensembl release 84

.travis.yml, pyensembl/ensembl_release_versions.py, test/test_transcript_ids.py
Bumping the max release to 85, fixes https://github.com/hammerlab/pyensembl/issues/161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/162)
=> Ensembl release 85

pyensembl/__init__.py, pyensembl/shell.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/174)
=> Fix logging file access in shell (needed pkg_resources)

RELEASING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/175)
=> err fixing number typo in RELEASING.md instructions

pyensembl/shell.py
fix typo in shell help message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/178)
=> fix typo in shell help message

.travis.yml
Partially addresses: https://github.com/hammerlab/pyensembl/issues/157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/179)
=> added caching to dir containing Ensembl downloads and database/indices

.travis.yml, pyensembl/__init__.py, pyensembl/ensembl_release_versions.py, pyensembl/species.py, test/test_download_cache.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hammerlab/pyensembl/183)
=> Add rat, dog, cat, chicken species & increase MAX_ENSEMBL_RELEASE to 87

.travis.yml, lint.sh
- Added vaxrank integration test; also changed PyPi user hammerlab -> openvax.
- Running pylint only on pyensembl files.
- Explicitly adding pip cache directory to Travis config.
=> More Travis updates

pyensembl/__init__.py, pyensembl/common.py, pyensembl/ensembl_release.py, pyensembl/genome.py, pyensembl/sequence_data.py, test/test_sequence_data.py
Issue: https://github.com/openvax/pyensembl/issues/209
=> Get rid of ensembl id validation

pyensembl/__init__.py, pyensembl/download_cache.py, pyensembl/genome.py, pyensembl/locus.py, pyensembl/species.py, pyensembl/transcript.py, test/test_locus.py
Removing non-debugging/testing use `assert` statements because @fabianegli is right (https://github.com/openvax/pyensembl/issues/227)
=> removed asserts in genome and locus

pyensembl/__init__.py, pyensembl/database.py, pyensembl/download_cache.py
https://github.com/openvax/pyensembl/issues/241
=> Only create cache dir for each Ensembl release if necessary

README.md
This is missing from the Readme but present in the API
=> Added exon_by_id function call

pyensembl/__init__.py, pyensembl/species.py
Add latest mouse release (GRCm39, Ensembl release 104).
=> Version 1.9.3

setup.py
=> Include requirements.txt in setup.py
